AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "lambda_function"
      Handler: "index.handler"
      Runtime: nodejs18.x
      Role: !Sub "arn:aws:iam::772776933351:role/CloudFormationExecutionRole"
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          GIT_TOKEN: !Sub "{{resolve:ssm-secure:/codepipeline/github/token}}"
          REPO_URL: !Sub "{{resolve:ssm:/codepipeline/github/repo}}"

Parameters:
  S3Bucket:
    Type: String
  S3Key:
    Type: String
